export const catagoryConstants = {
    GET_ALL_CATAGORIES_REQUEST: "GET_ALL_CATAGORIES_REQUEST",
    GET_ALL_CATAGORIES_SUCCESS: "GET_ALL_CATAGORIES_SUCCESS",
    GET_ALL_CATAGORIES_FAILURE: "GET_ALL_CATAGORIES_FAILURE",
    ADD_NEW_CATAGORIES_REQUEST: "ADD_NEW_CATAGORIES_REQUEST",
    ADD_NEW_CATAGORIES_SUCCESS: "ADD_NEW_CATAGORIES_SUCCESS",
    ADD_NEW_CATAGORIES_FAILURE: "ADD_NEW_CATAGORIES_FAILURE"
}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE"
}

export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const cartConstants = {
    CART_UPDATE_SUCCESS: "CART_UPDATE_SUCCESS",
    CART_UPDATE_FAILURE: "CART_UPDATE_FAILURE",
    CART_REQUEST_SUCCESS: "CART_REQUEST_SUCCESS",
    CART_REQUEST_FAILURE: "CART_REQUEST_FAILURE"
}

